name: Tests

env:
  PHPUNIT_FLAGS: "-v"
  SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
  SYMFONY_LTS: 4.4.*
  SYMFONY_LATEST: 5.2.*
  SYMFONY_NEXT: 5.3.*

on:
  push: ~
  release:
    types: [ created ]
  schedule:
    -   cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
  test:
    runs-on: ubuntu-latest

    name: "PHP ${{ matrix.php }}${{ matrix.symfony != '' && format(', Symfony {0}', matrix.symfony) || '' }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.3
            symfony: ${SYMFONY_LATEST}
          - php: 7.4
            symfony: ${SYMFONY_LTS}
          - php: 7.4
            symfony: ${SYMFONY_LATEST}
          - php: 7.4
            symfony: ${SYMFONY_NEXT}
          - php: 8.0
            symfony: ${SYMFONY_LATEST}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      - name: Restrict Symfony version
        if: matrix.symfony != ''
        run: |
          composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
          composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

      - name: Install dependencies
        run: composer update

      - name: Run PHPSpec
        run: bin/phpspec run --no-interaction -f dot

      - name: Install and build testing app
        run: |
          cd tests/app
          composer update
          yarn install
          yarn build
          cd ../../

      - name: Run PHPUnit
        run: bin/simple-phpunit -v
